//! User configuration, loaded from `$HERDR_PLUGIN_CONFIG_DIR/config.toml`.
//!
//! Every field has a default, so a missing or partial file is fine.

use std::collections::BTreeMap;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    pub general: General,
    pub label: Label,
    pub git: Git,
    pub ssh: Ssh,
    pub adoption: Adoption,
    /// Per-app icon/rank overrides, merged over the built-in table by app id.
    pub apps: BTreeMap<String, AppOverride>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct General {
    /// Coalescing window after an event burst before recomputing.
    pub debounce_ms: u64,
    /// Floor between two full passes, so a chatty agent cannot spin us.
    pub min_interval_ms: u64,
    /// How long a pane's process listing stays usable before we re-read it.
    pub process_ttl_ms: u64,
    /// Fallback poll when the event stream is unavailable. 0 disables it.
    pub poll_ms: u64,
    pub debug: bool,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Label {
    pub show_icon: bool,
    pub show_git: bool,
    pub show_folder: bool,
    /// Joins icon / git / folder segments.
    pub separator: String,
    /// Hard cap on the rendered label, in characters.
    pub max_length: usize,
    /// Shown instead of the folder when the directory is `$HOME`.
    pub home_symbol: String,
    pub ellipsis: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Git {
    pub branch_max: usize,
    /// What to render when sitting on the repository's default branch.
    pub default_branch_style: DefaultBranchStyle,
    /// Consulted when the repo has no `origin/HEAD` to read a default from.
    pub default_branches: Vec<String>,
    pub repo_glyph: String,
    pub branch_glyph: String,
    pub detached_glyph: String,
    /// Length of the abbreviated commit shown on a detached HEAD.
    pub detached_len: usize,
    /// How long a directory stays remembered as "not a repository", so a
    /// `git init` or a finished clone is picked up without a restart.
    pub recheck_non_repo_ms: u64,
    /// Where a *named* git segment sits relative to the folder. A glyph-only
    /// segment (the default-branch marker) always leads, since there is no
    /// name to set apart.
    pub position: GitPosition,
    /// Brackets around a named git segment. `["", ""]` removes them.
    ///
    /// herdr paints a tab label with a single style and never parses it, so
    /// colour cannot separate branch from folder - punctuation has to.
    pub wrap: [String; 2],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GitPosition {
    /// `api (\u{e725} feat/auth)`
    AfterFolder,
    /// `(\u{e725} feat/auth) api`
    BeforeFolder,
}

/// What to show when sitting on the repository's default branch.
///
/// Everything but `Name` shortens the label by dropping the branch name, at
/// the cost of the git fragment changing shape - and, because a glyph-only
/// marker leads while a named one trails, changing position too.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DefaultBranchStyle {
    /// ` folder` - repo glyph, branch name omitted.
    RepoGlyph,
    /// ` folder` - branch glyph, branch name omitted.
    BranchGlyph,
    /// `folder` - no git marker at all.
    Nothing,
    /// ` main folder` - spell the branch out like any other.
    Name,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Ssh {
    pub enabled: bool,
    /// Recover the remote directory from the title the remote shell sets.
    pub remote_folder_from_title: bool,
    /// Placed between host and remote folder.
    pub separator: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Adoption {
    pub mode: AdoptionMode,
    /// Extra labels to treat as herdr-generated, beyond the built-in list.
    pub generated_names: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AdoptionMode {
    /// Take over only labels that still look auto-generated by herdr.
    GeneratedOnly,
    /// Title every tab; back off permanently once a tab is renamed by hand.
    Always,
    /// Title nothing until a tab is adopted with the `adopt` action.
    OptIn,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct AppOverride {
    pub icon: Option<String>,
    pub rank: Option<i32>,
    /// Replaces the built-in process-name matches for this app.
    pub matches: Option<Vec<String>>,
}

impl Default for General {
    fn default() -> Self {
        Self {
            debounce_ms: 120,
            min_interval_ms: 250,
            process_ttl_ms: 1500,
            poll_ms: 0,
            debug: false,
        }
    }
}

impl Default for Label {
    fn default() -> Self {
        Self {
            show_icon: true,
            show_git: true,
            show_folder: true,
            separator: " ".to_string(),
            max_length: 32,
            home_symbol: "~".to_string(),
            ellipsis: "\u{2026}".to_string(),
        }
    }
}

impl Default for Git {
    fn default() -> Self {
        Self {
            branch_max: 12,
            default_branch_style: DefaultBranchStyle::Name,
            default_branches: ["main", "master", "trunk"]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            repo_glyph: "\u{f401}".to_string(),
            branch_glyph: "\u{e725}".to_string(),
            detached_glyph: "\u{f417}".to_string(),
            detached_len: 7,
            recheck_non_repo_ms: 10_000,
            position: GitPosition::AfterFolder,
            wrap: ["(".to_string(), ")".to_string()],
        }
    }
}

impl Default for Ssh {
    fn default() -> Self {
        Self {
            enabled: true,
            remote_folder_from_title: true,
            separator: ":".to_string(),
        }
    }
}

impl Default for Adoption {
    fn default() -> Self {
        Self {
            mode: AdoptionMode::GeneratedOnly,
            generated_names: Vec::new(),
        }
    }
}

impl Config {
    pub fn dir() -> Option<PathBuf> {
        std::env::var_os("HERDR_PLUGIN_CONFIG_DIR").map(PathBuf::from)
    }

    pub fn path() -> Option<PathBuf> {
        Self::dir().map(|d| d.join("config.toml"))
    }

    /// Loads the config, or returns the defaults with a warning on a bad file.
    /// A broken config must never take the tab bar down with it.
    pub fn load() -> Self {
        let Some(path) = Self::path() else {
            return Self::default();
        };
        let Ok(text) = std::fs::read_to_string(&path) else {
            return Self::default();
        };
        match toml::from_str::<Config>(&text) {
            Ok(cfg) => cfg,
            Err(e) => {
                eprintln!(
                    "herdr-tagr: {} is invalid, using defaults: {e}",
                    path.display()
                );
                Self::default()
            }
        }
    }
}
